# Generated by Django 5.1.5 on 2025-01-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategori',
            table='kategori',
        ),
        migrations.AlterModelTable(
            name='produk',
            table='produk',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
