# Generated by Django 4.2.18 on 2025-01-18 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_kategori_table_alter_produk_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.CASCADE, to='app.kategori'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
