# Generated by Django 4.2.18 on 2025-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_produk_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='id_kategori',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_status',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
